[package]
name = "rsgit"
version = "0.1.0"
authors = ["Eric Scouten <eric@scouten.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.9.0"
tempfile = "3.1.0"

[dev-dependencies]
dir-diff = "0.3.2"
