[package]
name = "rsgit"
version = "0.1.0"
authors = ["Eric Scouten <eric@scouten.com>"]
edition = "2018"

[dependencies]
sha-1 = "0.9.0"
tempfile = "3.1.0"
thiserror = "1.0.20"
unicode-normalization = "0.1.13"

[dev-dependencies]
dir-diff = "0.3.2"
